version: "3"

services:
  web:
    build: ./app
    # command: nodemon --inspect=0.0.0.0:5858
    volumes:
      - ./app:/code
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    volumes:
      - "db-data:/data/mongodb/db"


volumes:
  db-data:
